a,
.wr_goods .goods .item .text .prices .valid,
.xs_prices .valid,
.btn.empty,
.detail_more .tab_buttons li.active,
.detail_more .tab_buttons li:hover,
.wr_slider .slide .inner .invite span,
footer ul li a:hover,
.wr_news .news .item .predat strong:hover,
header .land .menu_wrapper_inner ul li a:hover,
.account a:hover,
.sky .post a:hover,
.account a.check-in:hover,
.search_result ul li a:hover,
.main_catalog .item .cont ul li a:hover,
.xs_sidebar .product-categories .current-cat > a,
.xs_sidebar .product-categories a:hover,
.title.arrows_field .tramp .char:hover,
.faq .question .name:hover,
.faq .question .name:hover .label,
.faq .active .question .name,
.faq .active .question .name .label,
.xs_sidebar .product_list_widget li .product-title:hover,
.xs_sidebar .widget_layered_nav ul li:hover,
.purchase .basket .text:hover .price,
.shop_table tr td.product-name > a:hover,
.main_catalog .item .cont .name:hover,
.product_info_container .product_sections a:hover
{color:#_#}

.btn,
.wr_goods .goods .item .text .lines .waterline a.compare:hover,
.wr_goods .goods .item .text .lines .waterline .basket:hover,
.purchase .common:hover,
.wr_slider .slick-dots li.slick-active button,
.social_links ul li a:hover,
input[type="text"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="password"]:focus,
input[type="email"]:focus,
textarea:focus,
.wr_brands .slick-arrow:hover,
.cbh-phone .cbh-ph-circle
{border-color:#_#}

.btn,
.purchase .common .much,
.detail_more .tab_buttons li.active:after,
.detail_more .xs_advantages ul li:after,
.detail_more .xs_advantages ul li:before,
.xs_learn_more a span.out .in,
.minder .subscribe .letter form input.sanding,
.wr_slider .slick-dots li.slick-active button,
.xs_sidebar .price_slider .ui-slider-range,
.footer .come-up.pc:hover,
.wr_brands .slick-arrow:hover,
#callbackMobile,
.cbh-phone .cbh-ph-img-circle,
.cbh-ph-circle-fill,
.main_catalog .item .cont .image .count
{background-color:#_#}

@media screen and (max-width:450px){
.wr_goods .goods .item .text .lines .waterline .basket
{background-color:#_#;border-color:#_#}
}

.social_links ul li a:hover svg
{fill:#_#}

.btn:hover
{border-color:#__#}

.btn:hover
{background-color:#__#}